version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login to Dockerhub
          command: echo "$DOCKER_PASSWORD" | base64 --decode | docker login -u "$DOCKER_USER" --password-stdin"
      - run:
          name: Build Docker container
          command: docker build -t navikt/uptimed:canary .
      - run:
          name: Push canary Docker container
          command: docker push navikt/uptimed:canary

