version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Setting application version
          command: echo 'export VERSION=$(cat ./version)' >> $BASH_ENV

      - run:
          name: Login to Dockerhub
          command: echo "$DOCKER_PASSWORD" | base64 --decode | docker login -u "$DOCKER_USER" --password-stdin

      - run:
          name: Build Docker container
          command: docker build -t navikt/uptimed:"$VERSION" .

      - run:
          name: Push Docker container
          command: docker push navikt/uptimed:"$VERSION"

      - run:
          name: Publish Release on GitHub
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./source*

      - run:
          name: Update version for next release
          command: |
            NEWVERSION=$((${VERSION}+1))
            echo ${NEWVERSION} > ./version
            git commit -a -m "Updated uptimed to version ${NEWVERSION}"
            git push
