version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Setting application version
          command: echo 'export VERSION=$(cat ./version)' >> $BASH_ENV

      - run:
          name: Login to Dockerhub
          command: echo "$DOCKER_PASSWORD" | base64 --decode | docker login -u "$DOCKER_USER" --password-stdin

      - run:
          name: Build Docker container
          command: docker build -t navikt/uptimed:"$VERSION" .

      - run:
          name: Publish Release on GitHub
          command: |
            git remote set-url origin https://${CIRCLE_PROJECT_USERNAME}:${GITHUB_TOKEN}@github.com/nais/uptimed
            git commit version -m "Release version ${VERSION} [skip ci]"
            git tag ${VERSION}
            git push && git push --tags

      - run:
          name: Push Docker container
          command: docker push navikt/uptimed:"$VERSION"

      - run:
          name: Update version for next release
          command: |
            NEWVERSION=$((${VERSION}+1))
            echo ${NEWVERSION} > ./version
            git commit -a -m "Updated uptimed to version ${NEWVERSION}"
            git push

      - run:
          name: Update version in nais-yaml
          command: |
            naisyaml=$(mktemp -d)
            git clone https://${CIRCLE_PROJECT_USERNAME}:${GITHUB_TOKEN}@github.com/navikt/nais-yaml $naisyaml
            cd $naisyaml
            sed -i 's/version.*/version\: '"${VERSION}"'/g' vars/uptimed.yaml
            git commit -a -m "Update uptimed to ${VERSION}"
            git push
