version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Setting application version
          command: echo 'export VERSION=$(cat ./version)' >> $BASH_ENV

      - run:
          name: Login to Dockerhub
          command: echo "$DOCKER_PASSWORD" | base64 --decode | docker login -u "$DOCKER_USER" --password-stdin

      - run:
          name: Build Docker container
          command: docker build -t navikt/uptimed:"$VERSION" .

      - run:
          name: Publish Release on GitHub
          command: |
            git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
            git tag -a ${VERSION} -m "Release uptimed ${VERSION} [skip ci]" && git push --tags https://$GITHUB_TOKEN@github.com/nais/uptimed

      - run:
          name: Push Docker container
          command: docker push navikt/uptimed:"$VERSION"

      - run:
          name: Update version in nais-yaml
          command: |
            git clone https://${CIRCLE_PROJECT_USERNAME}:${GITHUB_TOKEN}@github.com/navikt/nais-yaml && cd nais-yaml
            sed -i 's/version.*/version\: '"${VERSION}"'/g' vars/uptimed.yaml
            git commit -am "Update uptimed to ${VERSION}"
            git push

      - run:
          name: Update version for next release
          command: |
            NEWVERSION=$((${VERSION}+1))
            echo ${NEWVERSION} > ./version
            git commit -am "Updated uptimed next release to ${NEWVERSION} [skip ci]"
            git commit --amend --reset-author --no-edit
            git push https://$GITHUB_TOKEN@github.com/nais/uptimed
